import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import CustomCursor from "@/components/ui/CustomCursor";
import { Menu } from "@/components/ui/menu";
import DarkModeToggle from "@/components/DarkModeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
        <CustomCursor />
        {children}
        <Script
          src="https://chat.pixelgenius.ir/embed.js"
          strategy="afterInteractive"
          data-mode="floating"
          data-api-url="https://chat.pixelgenius.ir"
          data-login-url="https://chat.pixelgenius.ir/login"
          data-primary-color="#1B6BED"
          data-position="bottom-right"
          data-title="مشاوره با هوش مصنوعی نابغه پیکسل"
          data-subtitle="من همیشه آنلاین هستم تا توی پروژه‌ات کمکت کنم"
        />

        <Menu />
      </body>
    </html>
  );
}
